name: Automerge
on:
  issue_comment:
    types: [created]


jobs:
  find_comment:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/lgtm'
          prefix_only: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}

  check_permissions:
    runs-on: ubuntu-latest
    outputs:
      has_perms: ${{ steps.perms_check.conclusion == 'success' }}
    steps:
      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        id: perms_check
        continue-on-error: true
        with:
          permission: "admin"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}

  automerge:
    runs-on: ubuntu-latest
    needs: [find_comment, check_permissions]
    if: |
      needs.find_comment.outputs.triggered == 'true' &&
      needs.check_permissions.outputs.has_perms == 'true'
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_LABELS:
